name: vitrine-workflow
on: 
  push:
    branches:
      - 'master'
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Recupèration du code qui a déclenché l'action en cours
        uses: actions/checkout@v3
      - name: Fixe la version de  Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Récupère les lib dans le cache ou les réinstalle
        uses: actions/cache@v4
        with:
          path:  |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - name: Compile l'application avec la nouvelle version du code 
        run: npm ci
      - name: Construit une version de type production
        run: npm run build
      - name: Démarre ou redemarre le serveur d'application
        run: |
          if pm2 list | grep -q "vitrine-next"; then
            pm2 restart vitrine-next
          else
            pm2 start npm --name "vitrine-next" -- start -- -p 3000
          fi
