name: hello-world
on: push
jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /path/to/your/app
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: npm run build
