name: vitrine-workflow
on: push
jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /home/ysr/projects/actions-runner/_work/vitrine-next/vitrine-next
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Start or restart the app
        run: |
          if pm2 list | grep -q "nextjs-app"; then
            pm2 restart nextjs-app
          else
            pm2 start npm --name "nextjs-app" -- start -- -p 3000
          fi
