name: vitrine-workflow
on: push
jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /home/ysr/projects/actions-runner/_work/vitrine-next/vitrine-next
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        run: npm install --verbose
      - name: Build
        run: npm run dev
