name: vitrine-workflow
on: push
jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /home/ysr/projects/vitrine
    steps:
      - uses: actions/checkout@v3
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
