name: vitrine-workflow
on: push
jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /home/ysr/projects
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: '/home/ysr/projects'
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
