name: Jira Issue Transition

on:
  pull_request:
    types: [opened, edited,synchronized, closed, reopened]

jobs:
  jira-issue-transition:
    name: Transition Jira issue
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR Title contains Ticket
        id: checkPrTitle
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            fix
            feat
          scopes: |
            core
            ui
            SCRUM-\d+
          # Configure that a scope must always be provided.
          requireScope: true
          disallowScopes: |
            release
            [A-Z]+
          ignoreLabels: |
            bot
            ignore-semantic-pull-request

      - name: Jira Login
        id: jiraLogin
        if: steps.checkPrTitle.outcome == 'success'
        uses: frieder/gha-jira-login@v1
        env:
          JIRA_BASE_URL: ${{ vars.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ vars.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Transition Issue
        if: steps.jiraLogin.outcome == 'success'
        uses: frieder/jira-issue-transition@v1
        with:
          retries: 1
          retryDelay: 10
          timeout: 2000
          failOnError: true
          issue: ${{steps.checkPrTitle.outputs.scope}}
          transition: 21
